import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Ubuntu, Caveat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import LenisWrapper from "@/components/LenisWrapper";
import { ModeToggle } from "@/components/modeToggle";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
});
const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
  display: "swap",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="no-scrollbar">
      <body className={cn(inter.variable, ubuntu.variable, caveat.variable)}>
        <div className="bg-gray-600 dark:bg-gray-950 before:fixed before:inset-0 before:-z-40 dark:before:[background-image:url('/grainy-bg.svg')] dark:before:opacity-[.015]"></div>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <LenisWrapper>
            <div className="fixed w-fit top-2  left-1/5 z-10 ">
              <ModeToggle />
            </div>
            {children}
          </LenisWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
