import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Ubuntu } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import LenisWrapper from "@/components/LenisWrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
  display: "swap",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(inter.variable, ubuntu.variable)}>
      <body className={cn("antialiased font-ubuntu", ubuntu.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <LenisWrapper>{children}</LenisWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
